import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html
                lang="en"
                className="bg-slate-800"
            >
                <body className={inter.className}>
                    <main className="container mx-auto max-w-2xl mt-4 space-y-4 px-6">
                        <Toaster
                            position="top-center"
                            reverseOrder={false}
                            toastOptions={{
                                className: "w-full",
                            }}
                        />
                        {children}
                    </main>
                </body>
            </html>
        </ClerkProvider>
    );
}
